package Interfaz;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.KeyStroke;

import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/**
 *
 * @author Roberth Paul Loaiza Rosas -- Proyecto de biblioteca digital
 */
public class GAD_Loja extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public InputStream background = this.getClass().getResourceAsStream("/imagenes/background.png");
    public String filePath;

    public GAD_Loja() {
        initComponents();
        dim = super.getToolkit().getScreenSize();
        this.setSize(dim);
        cargarImagen(jDesktopPane1, background);

    }

    public static void cargarImagen(javax.swing.JDesktopPane jDeskp, InputStream fileImagen) {
        try {
            BufferedImage image = ImageIO.read(fileImagen);
            jDeskp.setBorder(new Fondo(image));
        } catch (Exception e) {
            System.out.println("Error, Imagen no disponible.");
        }
    }
    private Dimension dim;

    public void readPDF() {
        // build a controller
        SwingController controller = new SwingController();
        // Build a SwingViewFactory configured with the controller
        SwingViewBuilder factory = new SwingViewBuilder(controller);
        //with a complete, active Viewer UI.
        JPanel viewerComponentPanel = factory.buildViewerPanel();
        // add copy keyboard command
        ComponentKeyBinding.install(controller, viewerComponentPanel);

        // add interactive mouse link annotation support via callback
        controller.getDocumentViewController().setAnnotationCallback(
                new org.icepdf.ri.common.MyAnnotationCallback(
                        controller.getDocumentViewController()));

        // Create a JFrame to display the panel in
        JFrame window = new JFrame("Escuela Municipal Ecológica");
        window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        window.setLocation(80, 200);
        window.getContentPane().add(factory.buildCompleteMenuBar(), BorderLayout.NORTH);
        window.getContentPane().add(viewerComponentPanel, BorderLayout.CENTER);
        window.getContentPane().add(basurero, BorderLayout.AFTER_LINE_ENDS);

        window.pack();
        window.setVisible(true);

        // Open a PDF document to view
        // String sr = controller.getDocument().getDocumentOrigin();
        controller.openDocument(filePath);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basurero = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();

        basurero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/basurero.png"))); // NOI18N
        basurero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basureroActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Municipio de Loja");
        setAutoRequestFocus(false);
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jDesktopPane1.setDesktopManager(null);
        jDesktopPane1.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1200, 530));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Math2.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton4);
        jButton4.setBounds(360, 330, 60, 60);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Math3.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton5);
        jButton5.setBounds(430, 330, 60, 59);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Math4.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton6);
        jButton6.setBounds(510, 330, 70, 59);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Math5.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton7);
        jButton7.setBounds(600, 330, 60, 60);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Math6.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton8);
        jButton8.setBounds(670, 330, 60, 60);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Math3.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton14);
        jButton14.setBounds(830, 330, 70, 59);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Math4.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton13);
        jButton13.setBounds(920, 330, 60, 59);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Math5.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton12);
        jButton12.setBounds(1000, 330, 60, 60);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lite2.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton17);
        jButton17.setBounds(360, 450, 60, 60);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lite3.png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton18);
        jButton18.setBounds(430, 450, 60, 59);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lite4.png"))); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton19);
        jButton19.setBounds(510, 450, 60, 59);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lite5.png"))); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton20);
        jButton20.setBounds(590, 450, 60, 60);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lite6.png"))); // NOI18N
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton21);
        jButton21.setBounds(670, 450, 70, 60);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lite7.png"))); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton22);
        jButton22.setBounds(750, 450, 60, 60);

        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CN2.png"))); // NOI18N
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton30);
        jButton30.setBounds(350, 580, 60, 60);

        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CN3.png"))); // NOI18N
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton31);
        jButton31.setBounds(430, 580, 60, 59);

        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CN4.png"))); // NOI18N
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton32);
        jButton32.setBounds(510, 580, 60, 59);

        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CN5.png"))); // NOI18N
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton33);
        jButton33.setBounds(590, 580, 70, 60);

        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CN6.png"))); // NOI18N
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton34);
        jButton34.setBounds(670, 580, 70, 60);

        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CN7.png"))); // NOI18N
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton35);
        jButton35.setBounds(750, 580, 60, 60);

        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OP2.png"))); // NOI18N
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton37);
        jButton37.setBounds(350, 700, 60, 60);

        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OP3.png"))); // NOI18N
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton38);
        jButton38.setBounds(430, 700, 60, 59);

        jButton39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OP4.png"))); // NOI18N
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton39);
        jButton39.setBounds(510, 700, 70, 59);

        jButton40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OP5.png"))); // NOI18N
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton40);
        jButton40.setBounds(590, 700, 70, 60);

        jButton41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OP6.png"))); // NOI18N
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton41);
        jButton41.setBounds(670, 700, 60, 60);

        jButton42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OP7.png"))); // NOI18N
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton42);
        jButton42.setBounds(740, 700, 70, 60);

        jButton43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Math7.png"))); // NOI18N
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton43);
        jButton43.setBounds(750, 330, 70, 60);

        jButton46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lite3.png"))); // NOI18N
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton46);
        jButton46.setBounds(830, 450, 70, 59);

        jButton47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lite4.png"))); // NOI18N
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton47);
        jButton47.setBounds(920, 450, 60, 59);

        jButton48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lite5.png"))); // NOI18N
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton48);
        jButton48.setBounds(1000, 450, 60, 60);

        jButton60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CN3.png"))); // NOI18N
        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton60);
        jButton60.setBounds(830, 580, 60, 59);

        jButton61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CN4.png"))); // NOI18N
        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton61);
        jButton61.setBounds(920, 580, 60, 59);

        jButton62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CN5.png"))); // NOI18N
        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton62ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton62);
        jButton62.setBounds(1000, 580, 60, 60);

        jButton67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OP5.png"))); // NOI18N
        jButton67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton67ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton67);
        jButton67.setBounds(1000, 700, 60, 60);

        jButton68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OP4.png"))); // NOI18N
        jButton68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton68ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton68);
        jButton68.setBounds(920, 700, 60, 59);

        jButton69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OP3.png"))); // NOI18N
        jButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton69ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton69);
        jButton69.setBounds(830, 700, 70, 59);

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Math7.png"))); // NOI18N
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton27);
        jButton27.setBounds(850, 190, 60, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1339, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        filePath = "C:/Matematica7.pdf";
        readPDF();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/Lengua_2.pdf";
        readPDF();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void basureroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basureroActionPerformed
        // Tecla virtual de suprimir.

        try {
            Robot rob = new Robot();
            rob.keyPress(KeyEvent.VK_DELETE);
        } catch (Exception e) {
        }

        //   System.out.println("doing " + KeyEvent);

    }//GEN-LAST:event_basureroActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/Matematica_3.pdf";
        readPDF();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/Matematica_4.pdf";
        readPDF();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/Matematica_5.pdf";
        readPDF();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/Matematica_6.pdf";
        readPDF();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/Matematica_7.pdf";
        readPDF();
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/Matematica_cuaderno_5.pdf";
        readPDF();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/Matematica_cuaderno_6.pdf";
        readPDF();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/Matematica_cuaderno_7.pdf";
        readPDF();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/Lengua_3.pdf";
        readPDF();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/Lengua_4.pdf";
        readPDF();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/Lengua_5.pdf";
        readPDF();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/Lengua_6.pdf";
        readPDF();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/Lengua_7.pdf";
        readPDF();
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/Lengua_cuaderno_5.pdf";
        readPDF();
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/Lengua_cuaderno_6.pdf";
        readPDF();
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/Lengua_cuaderno_7.pdf";
        readPDF();
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCNN_2.pdf";
        readPDF();
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCNN_3.pdf";
        readPDF();
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCNN_4.pdf";
        readPDF();
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCNN_5.pdf";
        readPDF();
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCNN_6.pdf";
        readPDF();
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCNN_7.pdf";
        readPDF();
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCNN_cuaderno_7.pdf";
        readPDF();
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCNN_cuaderno_5.pdf";
        readPDF();
    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCNN_cuaderno_6.pdf";
        readPDF();
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCSS_2.pdf";
        readPDF();
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCSS_3.pdf";
        readPDF();
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCSS_4.pdf";
        readPDF();
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCSS_5.pdf";
        readPDF();
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCSS_6.pdf";
        readPDF();
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCSS_7.pdf";
        readPDF();
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton69ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCSS_cuaderno_5.pdf";
        readPDF();
    }//GEN-LAST:event_jButton69ActionPerformed

    private void jButton68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton68ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCSS_cuaderno_6.pdf";
        readPDF();
    }//GEN-LAST:event_jButton68ActionPerformed

    private void jButton67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton67ActionPerformed
        // TODO add your handling code here:
        filePath = "/Users/rploaiza10/Dropbox/NetBeansProjects/SchoolMunicipio/src/recursos/CCSS_cuaderno_7.pdf";
        readPDF();
    }//GEN-LAST:event_jButton67ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GAD_Loja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GAD_Loja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GAD_Loja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GAD_Loja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GAD_Loja().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton basurero;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
